FROM python:3

# -------------------
# Setting environment
# -------------------
ENV DOWNLOAD_TEMP=/downloads \
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/oracle/instantclient_19_8" \
    ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/19c/dbhome_1 \ 
    ORACLE_SITE_BASIC="https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip" \
    ORACLE_SITE_CLIENT="https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-basic-linux.x64-19.8.0.0.0dbru.zip?xd_co_f=fae07a5a-ae5f-4c1a-8ce0-f41ed4a394c5'" \
    PATH="$PATH:/opt/oracle/instantclient_19_8" \
    ORACLE_DB_HOST="localhost" \
    ORACLE_DB_PORT=1521 \
    ORACLE_SERVICE_NAME="xe" \
    ORACLE_DB_USER="C##GIOVANIPM" \
    ORACLE_DB_PASS="Pm11092j"

# ---------
# Update OS
# ---------
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y apt-utils && \
    apt-get install -y sudo && \
    apt-get install -y iputils-ping

# ----------------------
# Oracle Client 19.8.0.0
# ----------------------
RUN mkdir $DOWNLOAD_TEMP && \
    curl --progress-bar $ORACLE_SITE_CLIENT -o $DOWNLOAD_TEMP/instantclient-basic-linux.zip && \
    curl --progress-bar $ORACLE_SITE_BASIC -o $DOWNLOAD_TEMP/instantclient-sqlplus-linux.zip && \
    mkdir $ORACLE_BASE && \
    cd $DOWNLOAD_TEMP && \
    unzip $DOWNLOAD_TEMP/instantclient-basic-linux.zip -d $ORACLE_BASE && \
    unzip $DOWNLOAD_TEMP/instantclient-sqlplus-linux.zip -d $ORACLE_BASE

# --------------------
# Additional libraries
# --------------------
RUN apt-get install libaio1

# ---------------
# Setting workdir
# ---------------
WORKDIR /usr/src/app

# -----------------------
# Install python packages
# -----------------------
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# ---------
# Copy code
# ---------
COPY . .
COPY ./lib/*.py /usr/local/lib/python3.10

# ----
# Port
# ----
EXPOSE 8080

# -----------
# Server load
# -----------
CMD [ "python", "./main.py", "0.0.0.0:8080" ]