version: '3.8'

services:
  zeebe:
    image: camunda/zeebe:latest
    ports:
      - "26500:26500"
    environment:
      - ZEEBE_LOG_LEVEL=debug

  operate:
    image: camunda/operate:latest
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500

  tasklist:
    image: camunda/tasklist:latest
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500

  simple-monitor:
    image: camunda/zeebe-simple-monitor:latest
    ports:
      - "8083:8080"
    environment:
      - ZEEBE_ADDRESS=zeebe:26500
