apiVersion: v1
kind: ServiceAccount
metadata:
  name: iris-cloud-ops
  namespace: iko
  annotations:
    azure.workload.identity/client-id: "<UAMI_CLIENT_ID>"
    azure.workload.identity/tenant-id: "<AZURE_TENANT_ID>"
  labels:
    azure.workload.identity/use: "true"
