@echo off 
REM =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= 
REM RBST10164 
REM Capturado em: 06/03/2020 11:01 
REM =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= 
choco install Chocolatey -y 
choco install ActiveMQ -y 
choco install autohotkey.portable -y 
choco install batch-image-converter -y 
choco install boxes.portable -y 
choco install busybox -y 
choco install chocolatey -y 
choco install chocolatey-core.extension -y 
choco install chocolatey-dotnetfx.extension -y 
choco install chocolatey-windowsupdate.extension -y 
choco install curl -y 
choco install dia -y 
choco install docker-cli -y 
choco install docker-desktop -y 
choco install DotNet3.5 -y 
choco install DotNet4.5.2 -y 
choco install dotnet4.7.1 -y 
choco install dotnetfx -y 
choco install Everything -y 
choco install Firefox -y 
choco install gimp -y 
choco install gitkraken -y 
choco install graph -y 
choco install graphviz -y 
choco install grep -y 
choco install grepwin -y 
choco install javaruntime -y 
choco install jq -y 
choco install jre8 -y 
choco install KB2919355 -y 
choco install KB2919442 -y 
choco install KB2999226 -y 
choco install KB3033929 -y 
choco install KB3035131 -y 
choco install latexdraw -y 
choco install logexpert -y 
choco install mRemoteNG -y 
choco install PDFCreator -y 
choco install pencil -y 
choco install projectlibre -y 
choco install python2 -y 
choco install python3 -y 
choco install qtcreator -y 
choco install shman -y 
choco install sql-workbench -y 
choco install vcredist140 -y 
choco install vcredist2015 -y 
choco install vcredist2017 -y 
choco install vscode -y 
choco install vscode.install -y 
choco install Wget -y 
choco install winmerge -y 
choco install xmind -y 
choco install yed -y 
