@echo off 
choco install Chocolatey -y 
choco install autohotkey.portable -y 
choco install boxes.portable -y 
choco install chocolatey -y 
choco install chocolatey-core.extension -y 
choco install chocolatey-dotnetfx.extension -y 
choco install curl -y 
choco install docker-desktop -y 
choco install dotnet4.7.1 -y 
choco install dotnetfx -y 
choco install Firefox -y 
choco install gimp -y 
choco install gitkraken -y 
choco install grepwin -y 
choco install javaruntime -y 
choco install jq -y 
choco install jre8 -y 
choco install KB2919355 -y 
choco install KB2919442 -y 
choco install mRemoteNG -y 
choco install PDFCreator -y 
choco install projectlibre -y 
choco install python3 -y 
choco install shman -y 
choco install Wget -y 
choco install winmerge -y 
choco install xmind -y 
