import fineasylib

lista = fineasylib.listStatusTEDs()
print(lista)
lista = fineasylib.listStatusPagamentos()
print(lista)
lista = fineasylib.listStatusCobrancas()
print(lista)
lista = fineasylib.listStatusContas()
print(lista)
lista = fineasylib.listStatusPIX()
print(lista)
lista = fineasylib.listStatusClaims()
print(lista)
lista = fineasylib.listTypesClaims()
print(lista)
lista = fineasylib.listInfractionTypes()
print(lista)
lista = fineasylib.listInfractionReported()
print(lista)
lista = fineasylib.listInfractionStatus()
print(lista)