@echo off 
choco install Chocolatey -y 
choco install 7zip -y 
choco install 7zip.commandline -y 
choco install 7zip.install -y 
choco install 7zip.portable -y 
choco install atom -y 
choco install autohotkey.install -y 
choco install autohotkey.portable -y 
choco install boxes.portable -y 
choco install camstudio -y 
choco install celestia -y 
choco install chocolatey -y 
choco install chocolatey-core.extension -y 
choco install chocolatey-windowsupdate.extension -y 
choco install chocolateygui -y 
choco install codeblocks -y 
choco install ConEmu -y 
choco install db-visualizer -y 
choco install dbeaver -y 
choco install filezilla -y 
choco install filezilla.server -y 
choco install firebird -y 
choco install freesshd -y 
choco install gimp -y 
choco install git.install -y 
choco install gitlab-runner -y 
choco install gnucobol -y 
choco install golang -y 
choco install grepwin -y 
choco install hexchat -y 
choco install hmne -y 
choco install html-help-workshop -y 
choco install javaruntime -y 
choco install jre8 -y 
choco install julia -y 
choco install KB2919355 -y 
choco install KB2919442 -y 
choco install KB2999226 -y 
choco install KB3033929 -y 
choco install KB3035131 -y 
choco install lazarus -y 
choco install libreoffice-fresh -y 
choco install money-manager-ex -y 
choco install mpc-hc -y 
choco install mRemoteNG -y 
choco install mumble -y 
choco install notable -y 
choco install notepadplusplus -y 
choco install notepadplusplus.install -y 
choco install nsis -y 
choco install nsis.install -y 
choco install octave -y 
choco install octave.install -y 
choco install orwelldevcpp -y 
choco install PDFCreator -y 
choco install poweriso -y 
choco install projectlibre -y 
choco install puppet-bolt -y 
choco install pycharm-edu -y 
choco install python3 -y 
choco install ruby -y 
choco install ruby2.devkit -y 
choco install rufus -y 
choco install SQLite -y 
choco install sysinternals -y 
choco install tcpipmanager -y 
choco install tcpipmanager.install -y 
choco install tinycc -y 
choco install vcredist2015 -y 
choco install virtualbox -y 
choco install vscodium -y 
choco install Wget -y 
choco install winmerge -y 
choco install xmind -y 
