FROM python:3

# ---------
# Update OS
# ---------
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y apt-utils && \
    apt-get install -y sudo && \
    apt-get install -y iputils-ping

RUN pip install pyzmq && \
    pip install persizmq && \
    pip install Flask

COPY zmqserver.py /tmp/zmqserver.py

# Flask Port
EXPOSE 5000

# Zmq Sub Server
EXPOSE 4444

CMD ["python","/tmp/zmqserver.py"]